// AAC symbol vocabulary map.
// Keys are lowercase English words.
// Values are symbol filenames (without .png) — files live in public/symbols/
// sourced from the ARASAAC open symbol library (CC BY-NC-SA 4.0 — arasaac.org).

export const ALL_SYMBOL_MAP: Readonly<Record<string, string>> = {
  // Core verbs
  eat: 'eat',
  drink: 'drink',
  sleep: 'sleep',
  go: 'go',
  come: 'come',
  stop: 'stop',
  help: 'help',
  want: 'want',
  need: 'need',
  play: 'play',
  work: 'work',
  read: 'read',
  write: 'write',
  see: 'see',
  hear: 'hear',
  run: 'run',
  walk: 'walk',
  talk: 'talk',
  think: 'think',
  feel: 'feel',
  make: 'make',
  give: 'give',
  get: 'get',
  put: 'put',
  look: 'look',
  find: 'find',
  open: 'open',
  close: 'close',
  turn: 'turn',
  wait: 'wait',
  finish: 'finish',
  start: 'start',
  like: 'like',
  love: 'love',
  hurt: 'hurt',
  sit: 'sit',
  stand: 'stand',
  jump: 'jump',
  swim: 'swim',
  wash: 'wash',
  cook: 'cook',
  buy: 'buy',
  // Social / communication
  yes: 'yes',
  no: 'no',
  please: 'please',
  thank: 'thank',
  sorry: 'sorry',
  hello: 'hello',
  goodbye: 'goodbye',
  more: 'more',
  done: 'done',
  again: 'again',
  // Descriptors
  big: 'big',
  small: 'small',
  hot: 'hot',
  cold: 'cold',
  happy: 'happy',
  sad: 'sad',
  angry: 'angry',
  tired: 'tired',
  hungry: 'hungry',
  thirsty: 'thirsty',
  good: 'good',
  bad: 'bad',
  fast: 'fast',
  slow: 'slow',
  clean: 'clean',
  dirty: 'dirty',
  new: 'new',
  old: 'old',
  // Places and things
  home: 'home',
  school: 'school',
  food: 'food',
  water: 'water',
  bathroom: 'bathroom',
  bed: 'bed',
  car: 'car',
  book: 'book',
  phone: 'phone',
  table: 'table',
  chair: 'chair',
  door: 'door',
  window: 'window',
  // People
  mom: 'mom',
  dad: 'dad',
  friend: 'friend',
  teacher: 'teacher',
  doctor: 'doctor',
  boy: 'boy',
  girl: 'girl',
  baby: 'baby',
  // Animals
  dog: 'dog',
  cat: 'cat',
  bird: 'bird',
  fish: 'fish',
  // Time
  today: 'today',
  tomorrow: 'tomorrow',
  morning: 'morning',
  night: 'night',
}

// Subset used at 'key' density — high-frequency core AAC vocabulary
export const KEY_SYMBOL_WORDS: ReadonlySet<string> = new Set([
  'eat', 'drink', 'sleep', 'go', 'come', 'stop', 'help', 'want', 'need', 'play',
  'yes', 'no', 'please', 'more', 'done', 'again', 'thank', 'sorry', 'hello', 'goodbye',
  'happy', 'sad', 'hungry', 'thirsty', 'tired', 'hurt',
  'home', 'school', 'bathroom', 'bed',
  'mom', 'dad', 'friend', 'doctor',
  'good', 'bad', 'hot', 'cold', 'big', 'small',
])
